let id1 = document.getElementById("id1");
let sp1 = document.getElementById("sp1");
console.log(id1);
console.log(id2);
id1.matches(".box");
id2.matches(".box");
console.log(sp1.closest("#sp1"));
console.log(id1.contains(sp1));
console.log(sp1.contains(sp1));
console.log(sp1.contains(id1));
